# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='address',
            new_name='number',
        ),
    ]
